name: ControlORBle
main: feildmaster.OrbEnhance.plugin
version: 2.3 beta
author: feildmaster

commands:
  exp:
    description: View/Change experience
  exp-reload:
    description: Allows reload of exp config

permissions:
  orbEnhance.admin:
    default: op
    description: Allows player to change players experience