name: ControlORBle
main: feildmaster.controlorble.JavaPlugin
version: 2.4
author: feildmaster

commands:
  xp:
    description: Override vanilla xp command
  exp:
    description: View/Change experience
  exp-reload:
    description: Allows reload of exp config

permissions:
  orbEnhance.admin:
    default: op
    description: Allows player to change players experience